### ISSUE TITLE
No Timer is displayed

### ISSUE THREAD

**Issue by saminitz** [koehlertimo/pausentimer#3]
As you can see in the image below there is no timer displayed

<img width="1800" alt="Pausentimer No Timer" src="https://user-images.githubusercontent.com/49833818/206479293-9d862f58-c855-4fac-a803-ca9f2efb7689.png">

**Comment by koehlertimo** [comment]
@saminitz pls fix asap!!!

**Comment by koehlertimo** [comment]
😍
