### ISSUE TITLE
Link to a timer directly by custom urls

### ISSUE THREAD

**Issue by WuerfelDev** [koehlertimo/pausentimer#5]
Feature Request
Use a custom url to link to each timer. Something like
https://koehlertimo.github.io/pausentimer/#java
https://koehlertimo.github.io/pausentimer/#embedded
https://koehlertimo.github.io/pausentimer/#python

**Comment by koehlertimo** [comment]
@rbalexf can you do it?

**Comment by rbalexf** [comment]
I will gladly do this assignment

**Comment by koehlertimo** [comment]
changed my mind, dont do it! its not necessary! @rbalexf @WuerfelDev
